# Write your MySQL query statement below
SELECT F.QUERY_NAME ,ROUND(SUM((F.RATING)/(F.POSITION))/COUNT(S.QUERY_NAME),2) AS QUALITY ,
ROUND((100 * SUM(CASE WHEN F.RATING < 3 THEN 1 ELSE 0 END) / COUNT(F.QUERY_NAME)), 2) AS POOR_QUERY_PERCENTAGE
FROM QUERIES F
JOIN QUERIES S
ON F.QUERY_NAME = S.QUERY_NAME 
GROUP BY F.QUERY_NAME 