# Write your MySQL query statement below
SELECT P.PROJECT_ID ,ROUND(SUM(EXPERIENCE_YEARS)/COUNT(PROJECT_ID),2) AS AVERAGE_YEARS
FROM PROJECT P
JOIN EMPLOYEE E
ON P.EMPLOYEE_ID =E.EMPLOYEE_ID
GROUP BY PROJECT_ID