# Write your MySQL query statement below
SELECT R.CONTEST_ID , 
ROUND(COUNT(DISTINCT R.USER_ID) * 100/(SELECT COUNT(*) FROM USERS) ,2) AS PERCENTAGE
FROM REGISTER R
LEFT JOIN USERS U 
ON R.USER_ID = U.USER_ID
GROUP BY R.CONTEST_ID
ORDER BY PERCENTAGE DESC, CONTEST_ID ASC 